WebApp1/ViewModels/BreadcrumbViewModel.cs
namespace WebApp1.ViewModels
{
    public class BreadcrumbViewModel
    {
        public string? Title { get; set; }
    }
}

WebApp1/ViewModels/GridCollectionViewModel.cs
namespace WebApp1.ViewModels;

public class GridCollectionViewModel
{
    public string Title { get; set; } = "";
    public IEnumerable<string> Categories { get; set; } = null!;
    public IEnumerable<GridCollectionItemViewModel> GridItems { get; set; } = null!;
    public bool LoadMore { get; set; } = false;
}

WebApp1/ViewModels/PromotionViewModel.cs
namespace WebApp1.ViewModels
{
    public class PromotionViewModel
    {
        public IEnumerable<GridCollectionItemViewModel> PromotionItem_1 { get; set; } = null!;
        public IEnumerable<GridCollectionItemViewModel> PromotionItem_2 { get; set; } = null!;
    }
}

WebApp1/Controllers/ContactsController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp1.Services;
using WebApp1.ViewModels;

namespace WebApp1.Controllers
{
    public class ContactsController : Controller
    {
        private readonly ContactService _contactService;

        public ContactsController(ContactService contactService)
        {
            _contactService = contactService;
        }

        public IActionResult Index()
        {
            ViewData["Title"] = "Contact Us";

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                await _contactService.RegisterMessageAsync(viewModel);
                return RedirectToAction("Index", "Home"); 
            }
            return View(viewModel);
        }
    }
}

WebApp1/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp1.Services;
using WebApp1.ViewModels;

namespace WebApp1.Controllers
{
    public class LoginController : Controller
    {
        private readonly AuthenticationService _auth;

        public LoginController(AuthenticationService auth)
        {
            _auth = auth;
        }

        public IActionResult Index(string ReturnUrl = null!)
        {
            var viewModel = new LoginViewModel();
            if (ReturnUrl != null) 
                viewModel.ReturnUrl = ReturnUrl;

            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (await _auth.LoginAsync(viewModel))
                    return LocalRedirect(viewModel.ReturnUrl);

                ModelState.AddModelError("", "Incorrect e-mail or password");
            }

            return View(viewModel);
        }
    }
}

WebApp1/Controllers/LogoutController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebApp1.Models.Identity;

namespace WebApp1.Controllers
{
    public class LogoutController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;

        public LogoutController(SignInManager<AppUser> signInManager)
        {
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Index()
        {
            if(_signInManager.IsSignedIn(User))
                await _signInManager.SignOutAsync();
            return LocalRedirect("/");
        }
    }
}

WebApp1/Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp1.ViewModels;
using WebApp1.Services;

namespace WebApp1.Controllers
{
    public class RegisterController : Controller
    {
        private readonly AuthenticationService _auth;

        public RegisterController(AuthenticationService auth)
        {
            _auth = auth;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(RegisterViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (await _auth.UserAlreadyExistsAsync(x => x.Email == viewModel.Email))
                    ModelState.AddModelError("", "An account with the same e-mail already exists.");
 
                if (await _auth.RegisterUserAsync(viewModel))
                    return RedirectToAction("index", "login");
            }

            return View(viewModel);
        }
    }
}

WebApp1/Views/Partials/_Breadcrumb.cshtml
<section class="breadcrumb">
    <div class="container">
        <div class="content">
            <h1>@ViewData["Title"]</h1>
        </div>
    </div>
</section>

WebApp1/Views/Partials/_Footer.cshtml
<footer>
    <div class="container">
        Ⓒ @DateTime.Now.ToString("yyyy") Bmerketo - All right reserved.
    </div>
</footer>

WebApp1/Views/Partials/_GridCollection.cshtml
@model GridCollectionViewModel  

@if (Model != null)
{
    <section class="grid-collection">
        <div class="container">
            @if (!string.IsNullOrEmpty(Model.Title))
            {
                <h1 class="title">@Model.Title</h1>
            }

            @if (Model.Categories != null)
            {
                <ul class="categories">
                    @foreach (var category in Model.Categories)
                    {
                        <li class="category-item">@category</li>
                    }
                </ul>
            }

            @if (Model.GridItems != null)
            {
                <div class="grid">
                    @foreach (var item in Model.GridItems)
                    {
                        <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                    }
                </div>
            }

            @if (Model.LoadMore)
            {
                <div class="load-more">
                    <button class="btn-outline-white">LOAD MORE <i class="fa-solid fa-rotate-right"></i></button>
                </div>
            }

        </div>
    </section>
}

WebApp1/Views/Partials/_Header.cshtml
<header>
    <div class="container">
        <a class="logo" asp-controller="Home" asp-action="Index"><img src="images/logo.svg" alt="">bmerketo</a>
        <nav id="menu" class="menu-links">
            <a class="link" asp-controller="Home" asp-action="Index">HOME</a>
            <a class="link" asp-controller="Products" asp-action="Index">PRODUCTS</a>
            <a class="link" asp-controller="Contacts" asp-action="Index">CONTACT</a>
        </nav>
        <nav class="menu-icons">
            <a class="link" asp-controller="Products" asp-action="Search"><i class="fa-regular fa-search"></i></a>

            <div class="dropdown">
                <a class="link dropdown-toggle" href="#" role="button" id="account-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa-solid fa-user"></i>
                </a>
                <div class="dropdown-menu" aria-labelledby="account-dropdown">
                    
                    @if (signInManager.IsSignedIn(User))
                    {
                        <a class="dropdown-item" asp-controller="Account" asp-action="Index">Your Account</a>
                        <a class="dropdown-item" asp-controller="Logout" asp-action="Index">Logout</a>
                    }
                    else
                    {   <a class="dropdown-item" asp-controller="Login" asp-action="Index">Login</a>
                        <a class="dropdown-item" asp-controller="Register" asp-action="Index">Register</a>
                    }
                    
                </div>
            </div>

            <a class="link" asp-controller="Cart" asp-action="Index"><i class="fa-solid fa-cart-shopping"></i></a>
        </nav>
        <div class="toggle">
            <button class="btn-toggle btn-outline-white" data-option="toggle" data-target="#menu">
                <i id="icon" class="fa-regular fa-bars"></i>
            </button>
        </div>
    </div>
</header>

WebApp1/Views/Partials/_Promotion.cshtml
@model PromotionViewModel

@{
    var discover = discoverService.GetDiscovers();
}


<section class="promotion">
    <div class="container">
        <div class="collection-grid">
            <div class="item-1">
                @if (Model.PromotionItem_1 != null)
                {
                    <div class="grid">
                        @foreach (var item in Model.PromotionItem_1)
                        {
                            <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                        }
                    </div>
                }
            </div>

            <div class="discover">
                <div class="collection-content">
                    <div class="container">
                        <div class="title">@discover?.Title</div>
                        <div class="discount-percent">@discover?.DiscountPercent</div>
                        <div class="ingress">@discover?.Ingress</div>
                        <div class="text">@discover?.Text</div>

                        @if (!string.IsNullOrEmpty(discover?.Button?.Url) && !string.IsNullOrEmpty(@discover?.Button?.Content))
                        {
                            <a href="@discover?.Button?.Url" class="btn-theme">@discover?.Button?.Content</a>
                        }

                    </div>
                </div>
            </div>

                <div class="item-2">
                @if (Model.PromotionItem_2 != null)
                    {
                        <div class="grid">
                            @foreach (var item in Model.PromotionItem_2)
                            {
                                <partial name="/Views/Partials/_GridCollectionItem.cshtml" model="item" />
                            }
                        </div>
                    }
                </div>
            </div>
        </div>
</section>